include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [lib/generated/**]
  language:
    #  strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - camel_case_types
    - implicit_call_tearoffs
    - prefer_expression_function_bodies
    - unnecessary_late
    - unnecessary_lambdas
    - type_annotate_public_apis
