name: pks_edit_flutter
description: "A code editor implemented in Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.9.0
  charset: ^2.0.1
  rxdart: ^0.28.0
  http: ^1.2.1
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  re_editor: ^0.4.0
  multi_split_view: ^3.1.0
  window_manager: ^0.4.2
  re_highlight: ^0.0.3
  collection: ^1.18.0
  path: ^1.8.2
  jovial_svg: ^1.1.21
  flutter_markdown: ^0.7.1
  sound_library: ^1.0.0
  font_awesome_flutter: ^10.6.0
  font_awesome_flutter_named: ^1.1.2+1
  material_icons_named: ^3.16.0
  logger: ^2.4.0
  file_selector: ^1.0.3
  flutter_highlight: ^0.7.0
  super_drag_and_drop: ^0.8.11
  intl_utils: ^2.8.7
  intl: ^0.19.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.3.3

flutter_intl:
  enabled: true
  main_locale: en

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
